muza-music/muza-lit-library

.gitignore, index.html, package-lock.json, src/MusicSection.ts, src/VolumeControl.ts
fix toggle volume button, fix scroll and fix headers colors
Scrrenshots:
Before:
After:
=> fix toggle volume button, fix scroll and fix headers colors

.github/workflows/pull-request.yml, src/MusicSection.ts, src/MusicSidebar.ts, src/MusicTopbar.ts, src/VolumeControl.ts
=> Add a pull request workflow

.prettierrc, eslint.config.js, package-lock.json, package.json, src/MusicAlbum.ts, src/MusicSection.ts, src/MusicSidebar.ts, src/MusicTopbar.ts, src/SongLine.ts, src/VolumeControl.ts, src/index.ts, tests/MusicAlbum.test.ts
Issue:
Linter rules are too relaxed
Fix:
Add more linting roles
=> add-lint-rules

data/albums.json, data/songs.json, index.html
I added json data for albums and songs. In the index.html file i used a simulated api call to the json data instead of the previous hardcoded data.
=> Simulate api requests

data/sidebar.json, index.html, src/MusicAlbum.ts, src/MusicSection.ts, src/SongLine.ts, src/styles/variables.css
Add CSS variable file
in components
in the demo file
Screenshot:
=> Add css vars

index.html, src/MusicPlayer.ts, src/index.ts
Song Player - the player by the design and button events 
appears when an album is clicked
things to be decided:
is the player starts when we click an album?
is the sound player itself and it's queue will be managed inside the component?
the event structure for the song data
=> MusicPlayer with audio 

data/songs.json, index.html, src/MusicPlayer.ts, src/SongLine.ts, src/styles/variables.css
Update music player component
Screenshot:
https://github.com/user-attachments/assets/21014819-011a-4892-b067-2b9bd86bf622
=> Update music player

index.html
=> fix indentation in index file

index.html, src/MusicPlayer.ts, src/SongLine.ts, src/models.ts
added song line play mode with animation provided by the UI desinger.
added function to the Player component for song-lines updating when a new song is loaded.
added indexing for the song lines.
=> playing mode to song line

src/SmallAlbumDetails.ts
adding small album details for the playlist title
=> small album details

index.html, src/AlbumDetails.ts, src/SongLine.ts, src/index.ts
added the head of the album page 
fixed song line css
=> album page head

index.html, src/MusicPlaylist.ts, src/MusicSuggestionsList.ts, src/MuzaButton.ts, src/SuggestionsListItem.ts, src/styles/scrollbar.css, src/styles/variables.css
add 
1. suggestionslist
2. suggestions list item
3. and side play list
=> playlist and suggestions

data/albums.json, index.html, src/components/albumDisplays/AlbumCover.ts, src/components/albumDisplays/PlaylistCover.ts, src/components/listsDisplays/MusicListSection.ts, src/icons/Playlist.ts, src/index.ts, tests/MusicAlbum.test.ts
music section rename
playlist section option added 
playlist icon change
=> playlist icon change

data/artists.json, index.html, src/components/albumDisplays/AlbumArtist.ts, src/components/listsDisplays/MusicListSection.ts, src/index.ts, tests/MusicAlbum.test.ts
I created albumArtist  type,  added it to musicListComponent with json data and tests
=> add album artist

index.html, src/controls/ToggleButton.ts, src/styles/variables.css
Added toggle button according to the figma design. (the line in the picture is from the cmp below it)
=> Add toggle button

server/index.js
Issue:
DB is read only once, no updates
Fix:
read DB on every call
=> Live update of data

app/appData/models.ts, app/components/listsDisplays/MusicListSection.tsx, app/routes/home.tsx
Enhance MusicListSection to support song display and improve home coponent structure
- Updated MusicListSection to include a new "song" type for rendering song details.
- Refactored the home component to utilize MusicListSection for displaying albums, songs, and artists dynamically.
- Introduced a sections configuration to streamline the rendering process and improve code organization.
=> Fixed Home.tsx to support list

app/app.scss, app/components/listsDisplays/MusicListSection.scss, app/components/sections/MusicPlayer.scss, app/components/sections/MusicPlayer.tsx, app/root.tsx
implemented the design of the music player by figma using the figma mcp. Also made some general vars reset in the main app.scss file
=> Music player style

app/components/sections/MusicSidebar.tsx, app/components/sections/MusicTopbar.tsx, app/root.tsx
Refactor Layout component to streamline state management by directly accessing store state; update MusicSidebar and MusicTopbar components to use React.memo for performance optimization.
=> Fixed glitches in rerendering

app/components/albumDisplays/AlbumInfoModal.scss
fixed the header in the playlistd by scoping it in the album header modal
=> Refactor AlbumInfoModal styles for improved structure and readability

app/components/songLineDisplays/SongDetails.scss, app/routes/songs.scss, app/routes/songs.tsx
- Removed background color from SongDetails.scss for a cleaner look.
- Adjusted padding and margin in songs.scss to improve layout and responsiveness.
- Replaced SongDetails component with SongLineWithCover in songs.tsx for enhanced song display functionality.
=> refactor: update song details display and styles

app/components/albumDisplays/AlbumDetails.scss, app/components/albumDisplays/AlbumDetails.tsx, app/components/ui/HoverOverlay.scss, app/components/ui/HoverOverlay.tsx
Refactor: Update AlbumDetails and HoverOverlay components for improved styling and functionality
- Removed background styles from AlbumDetails and HoverOverlay SCSS files for a cleaner look.
- Reorganized action buttons in AlbumDetails to enhance user experience.
- Adjusted HoverOverlay styles for better button dimensions and hover effects.
- Updated comments in HoverOverlay to reflect the new button positioning.
=> Album-overly
